FROM python:3.5

RUN adduser --disabled-login --disabled-password server

WORKDIR /home/server

COPY requirements.txt ./
RUN python -m venv venv
RUN venv/bin/pip install --no-cache-dir -r requirements.txt
RUN venv/bin/pip install gunicorn

COPY app app

#COPY migrations migrations
COPY server.py config.py docker/boot.sh .env ./
RUN chmod +x boot.sh

RUN chown -R server:server ./
USER server

EXPOSE 5000

CMD ["./boot.sh"]
